### ISSUE TITLE
Make a Readme file

### ISSUE THREAD

**Issue by Damien-MATHIEU** [benchttp/webapp#71]
## Description

Document the repository.

## Tasks

The file contains at least:
- [x] A presentation of the repository
- [x] How to connect
- [x] Usage
- [x] A link to the other repositories
